# Generated by Django 5.2.4 on 2025-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcart', '0002_remove_profile_full_name_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
