# Generated by Django 5.2.4 on 2025-08-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojectapp', '0004_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
