# Generated by Django 5.2.4 on 2025-08-29 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojectapp', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.CreateModel(
            name='MegaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mega_menu/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_menu_items', to='gprojectapp.category')),
            ],
        ),
    ]
