# Generated by Django 5.2.4 on 2025-08-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gprojectapp', '0006_remove_category_image_megamenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MegaMenu',
        ),
    ]
