# Generated by Django 5.2.4 on 2025-09-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojectapp', '0007_delete_megamenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
