# Generated by Django 5.2.4 on 2025-09-04 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprojectapp', '0008_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='megamenu', to='gprojectapp.category')),
            ],
            options={
                'verbose_name': 'Mega Menu',
                'verbose_name_plural': 'Mega Menus',
            },
        ),
    ]
